'use strict';
const escapeHTML = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function safeURL(value) {
  if (!value || typeof value !== 'string') return '';
  try { const url = new URL(value, location.href); return ['http:', 'https:'].includes(url.protocol) ? url.href : ''; } catch { return ''; }
}
const external = (url, label, cls = '') => safeURL(url) ? `<a class="${cls}" href="${escapeHTML(safeURL(url))}" target="_blank" rel="noopener noreferrer">${escapeHTML(label)}</a>` : '';
const tags = items => `<div class="tags">${items.map(item => `<span class="tag">${escapeHTML(item)}</span>`).join('')}</div>`;
const currentPage = document.body.dataset.page || 'home';
const draftMode = new URLSearchParams(location.search).get('draft') === '1';
function localLink(path) { return draftMode ? path + (path.includes('?') ? '&' : '?') + 'draft=1' : path; }
function header(profile) {
  const nav = [['home','index.html','Home'],['about','about.html','About'],['projects','projects.html','Projects'],['contact','contact.html','Contact']];
  return `<header class="header"><div class="wrap header-inner"><a class="brand" href="${localLink('index.html')}" aria-label="${escapeHTML(profile.name)} home">${escapeHTML(profile.brand)}<span>${escapeHTML(profile.brandSuffix)}</span></a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="navigation">Menu</button><nav id="navigation" class="nav" aria-label="Main navigation">${nav.map(([id,url,label])=>`<a href="${localLink(url)}" ${currentPage===id || currentPage==='project'&&id==='projects'?'aria-current="page"':''}>${label}</a>`).join('')}${external(profile.resume,'Résumé','resume')}</nav></div></header>`;
}
function footer(p) { return `<footer class="footer"><div class="wrap"><div class="footer-grid"><div><a class="brand" href="${localLink('index.html')}">${escapeHTML(p.brand)}<span>${escapeHTML(p.brandSuffix)}</span></a><p>${escapeHTML(p.footer)}</p></div><div><h3>Navigation</h3><div class="footer-links"><a href="${localLink('about.html')}">About</a><a href="${localLink('projects.html')}">Projects</a><a href="${localLink('contact.html')}">Contact</a></div></div><div><h3>Connect</h3><div class="footer-links">${external(p.github,'GitHub')}${external(p.linkedin,'LinkedIn')}${p.email?`<a href="mailto:${escapeHTML(p.email)}">Email</a>`:''}</div></div></div><div class="copyright">© ${new Date().getFullYear()} ${escapeHTML(p.name)}. All rights reserved.</div></div></footer>`; }
function expertise(data) { return `<section class="section"><h2 class="section-title">${escapeHTML(data.pages.expertiseTitle)}</h2><div class="expertise-grid">${data.expertise.map((group,i)=>`<article class="panel"><span class="skill-symbol" aria-hidden="true">${['⌘','◎','⊞','&lt;/&gt;'][i%4]}</span><h3>${escapeHTML(group.title)}</h3>${tags(group.items)}</article>`).join('')}</div></section>`; }
function projectCard(p) { const image=safeURL(p.image); return `<article class="panel project-card">${image?`<img class="project-image" src="${escapeHTML(image)}" alt="${escapeHTML(p.imageAlt||p.title)}" loading="lazy">`:''}<div class="eyebrow">${escapeHTML(p.category)}</div><h3><a href="${localLink('project.html?id='+encodeURIComponent(p.id))}">${escapeHTML(p.title)}</a></h3><p>${escapeHTML(p.summary)}</p>${tags(p.tags)}<a class="project-link" href="${localLink('project.html?id='+encodeURIComponent(p.id))}">View Project <span aria-hidden="true">→</span></a></article>`; }
function home(data) { const p=data.profile; return `<main id="main"><div class="wrap"><section class="hero"><div class="badge">${escapeHTML(p.role)}</div><h1>${escapeHTML(p.name)}</h1><h2 class="headline">${escapeHTML(p.headline)} <span>${escapeHTML(p.headlineAccent)}</span></h2><p class="hero-intro">${escapeHTML(p.intro)}</p><div class="actions"><a class="button primary" href="${localLink('projects.html')}">View My Work</a><a class="button" href="${localLink('about.html')}">About Me</a>${external(p.linkedin,'LinkedIn','button')}</div><div class="tech-strip"><div class="eyebrow">Core Technologies</div><div class="tech-list">${data.technologies.map(t=>`<span>${escapeHTML(t)}</span>`).join('')}</div></div></section>${expertise(data)}<section class="section"><h2 class="section-title">${escapeHTML(data.pages.featuredTitle)}</h2><div class="projects-grid">${data.projects.filter(p=>p.featured).map(projectCard).join('')}</div><div class="actions"><a class="button" href="${localLink('projects.html')}">View All Projects <span aria-hidden="true">→</span></a></div></section><section class="section"><h2 class="section-title">${escapeHTML(data.pages.quickLinksTitle)}</h2><div class="quick-grid">${[['about.html','About Me','Experience & education'],['projects.html','Projects','Robotics & vision work'],['contact.html','Contact','Get in touch']].map(([url,title,desc])=>`<a class="panel quick" href="${localLink(url)}"><div><strong>${title}</strong><p>${desc}</p></div><span aria-hidden="true">↗</span></a>`).join('')}</div></section></div></main>`; }
function heading(title,intro) { return `<div class="page-heading"><h1>${escapeHTML(title)}</h1><p>${escapeHTML(intro)}</p></div>`; }
function about(data) { const p=data.profile; return `<main id="main" class="wrap">${heading(data.pages.aboutTitle,data.pages.aboutIntro)}<section class="section about-intro"><div class="prose">${p.about.map(t=>`<p>${escapeHTML(t)}</p>`).join('')}<div class="meta">${escapeHTML(p.location)}</div>${external(p.resume,'Download Résumé','button')}</div>${safeURL(p.portrait)?`<img class="portrait" src="${escapeHTML(safeURL(p.portrait))}" alt="${escapeHTML(p.name)}">`:''}</section><section class="section"><h2 class="section-title">Experience</h2><div class="timeline">${data.experience.map(e=>`<article class="panel experience"><h3>${escapeHTML(e.role)}</h3><div class="organization">${escapeHTML(e.organization)}</div><div class="meta">${escapeHTML(e.period)}${e.location?' · '+escapeHTML(e.location):''}</div><p>${escapeHTML(e.description)}</p></article>`).join('')}</div></section><section class="section"><h2 class="section-title">Education</h2><div class="education-grid">${data.education.map(e=>`<article class="panel"><div class="meta">${escapeHTML(e.period)}</div><h3>${escapeHTML(e.degree)}</h3><div class="organization">${escapeHTML(e.institution)}</div><p>${escapeHTML(e.description)}</p></article>`).join('')}</div></section>${expertise(data)}</main>`; }
function projects(data) { return `<main id="main" class="wrap">${heading(data.pages.projectsTitle,data.pages.projectsIntro)}<section class="section"><div class="projects-grid">${data.projects.map(projectCard).join('')}</div>${!data.projects.length?'<p class="empty">Projects will be shared here soon.</p>':''}</section></main>`; }
function contact(data) {const p=data.profile;return `<main id="main" class="wrap">${heading(data.pages.contactTitle,data.pages.contactIntro)}<div class="contact-grid"><section class="panel contact-card"><div class="eyebrow">Get in touch</div><h2>Let’s talk robotics.</h2><p>${escapeHTML(p.location)}</p>${p.email?`<p><a href="mailto:${escapeHTML(p.email)}">${escapeHTML(p.email)}</a></p><a class="button primary" href="mailto:${escapeHTML(p.email)}">Send an Email <span aria-hidden="true">↗</span></a>`:''}</section><section class="contact-links" aria-label="Professional profiles">${safeURL(p.linkedin)?`<a class="panel quick" href="${escapeHTML(safeURL(p.linkedin))}" target="_blank" rel="noopener noreferrer"><strong>LinkedIn <span aria-hidden="true">↗</span></strong><p>Experience, updates, and conversations</p></a>`:''}${safeURL(p.github)?`<a class="panel quick" href="${escapeHTML(safeURL(p.github))}" target="_blank" rel="noopener noreferrer"><strong>GitHub <span aria-hidden="true">↗</span></strong><p>Code, experiments, and robotics projects</p></a>`:''}</section></div></main>`;}
function project(data) { const id=new URLSearchParams(location.search).get('id'),p=data.projects.find(x=>x.id===id);if(!p){document.title='Project not found | '+data.profile.name;return `<main id="main" class="wrap">${heading('Project not found','This project may have been renamed or removed.')}<div class="center"><a class="button primary" href="${localLink('projects.html')}">Browse Projects</a></div></main>`;}document.title=p.title+' | '+data.profile.name;return `<main id="main" class="wrap detail"><a class="back" href="${localLink('projects.html')}">← All Projects</a><section class="section"><div class="eyebrow">${escapeHTML(p.category)}</div><h1>${escapeHTML(p.title)}</h1>${tags(p.tags)}<p>${escapeHTML(p.summary)}</p>${safeURL(p.image)?`<img class="detail-image" src="${escapeHTML(safeURL(p.image))}" alt="${escapeHTML(p.imageAlt||p.title)}">`:''}<h2>Overview</h2><p>${escapeHTML(p.overview)}</p>${p.contributions.length?`<h2>My Contribution</h2><ul>${p.contributions.map(x=>`<li>${escapeHTML(x)}</li>`).join('')}</ul>`:''}${p.results?`<h2>Results & Learnings</h2><p>${escapeHTML(p.results)}</p>`:''}<div class="actions">${external(p.repository,'View Code on GitHub','button primary')}${external(p.demo,'Watch Demo','button')}</div></section></main>`;}
async function loadPortfolio(){try{let data;if(draftMode){const draft=sessionStorage.getItem('portfolioDraft');if(draft)data=JSON.parse(draft);}if(!data){const response=await fetch('content.json',{cache:'no-cache'});if(!response.ok)throw new Error('Content unavailable');data=await response.json();}document.title=(currentPage==='home'?data.profile.name+' | Robotics Engineer':currentPage.charAt(0).toUpperCase()+currentPage.slice(1)+' | '+data.profile.name);document.querySelector('meta[name=description]').content=data.profile.intro;const renderers={home,about,projects,contact,project};const content=(renderers[currentPage]||home)(data);document.getElementById('site').innerHTML=(draftMode?'<div class="preview-banner">Private draft preview. Changes are not published. <a href="editor.html">Back to editor</a></div>':'')+header(data.profile)+content+footer(data.profile);const menu=document.querySelector('.menu-toggle'),nav=document.querySelector('.nav');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open);});document.addEventListener('keydown',e=>{if(e.key==='Escape'){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');}});document.querySelectorAll('img').forEach(img=>img.addEventListener('error',()=>img.remove(),{once:true}));}catch(error){document.getElementById('site').innerHTML='<main id="main" class="wrap"><section class="section"><h1>Portfolio content could not load</h1><p>Please reload the page. For local preview, run a local web server as described in README.md.</p><a href="https://www.linkedin.com/in/souvik-roy57/">Find Souvik on LinkedIn</a></section></main>';console.error(error);}}
loadPortfolio();
